configs:
  - id: outbound-connections
    config:
      template: outbound-connections.json
      parameters:
        connectionList:
          type: list
          values:
            - slack.com
            - "4.156.112.213"
            - yo-this-is-public.s3.eu-central-1.amazonaws.com
      skip: false
    type:
      settings:
        schema: builtin:dt-javascript-runtime.allowed-outbound-connections
        scope: environment
