name: Deploy Easytrade
run-name: Deploy Easytrade
on: 
  workflow_dispatch:
    inputs:
      failure:
        description: "simulate bad code"
        required: true
        default: true
        type: boolean
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      startTime: ${{ steps.set-start-end-time.outputs.startTime }}
      endTime: ${{ steps.set-start-end-time.outputs.endTime }}
    steps:
      - name: "Set start/end time for evaluation"
        id: set-start-end-time
        run: |
          start=$(date -d '3 minute ago' --utc +%FT%TZ)
          echo "startTime=$start" >> $GITHUB_OUTPUT
          end=$(date --utc +%FT%TZ)
          echo "endTime=$end" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: "Load Test - Failure"
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: /github/workspace/loadtesting/failure.jmx
        if: ${{inputs.failure == true}}
      - name: "Load Test - Success"
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: /github/workspace/loadtesting/success.jmx
        if: ${{inputs.failure == false}}

  evaluation:
    needs: [setup, test]
    runs-on: ubuntu-latest
    container:
      image: "dynatraceace/dt-automation-cli:latest"
    steps:
      - name: "Run SRG evaluation"
        run: |
          dta srg evaluate
        env:
          LOG_LEVEL: "verbose"
          DYNATRACE_URL_GEN3: ${{ secrets.DYNATRACE_URL_GEN3 }}
          ACCOUNT_URN: ${{ secrets.ACCOUNT_URN }}
          DYNATRACE_CLIENT_ID: ${{ secrets.DYNATRACE_CLIENT_ID }}
          DYNATRACE_SECRET: ${{ secrets.DYNATRACE_SECRET }}
          DYNATRACE_SSO_URL: ${{ secrets.DYNATRACE_SSO_URL }}
          SRG_EVALUATION_STOP_ON_FAILURE: "true"
          SRG_EVALUATION_SERVICE: "database"
          SRG_EVALUATION_STAGE: "prod"
          SRG_EVALUATION_START_TIME: "${{ needs.setup.outputs.startTime }}"
          SRG_EVALUATION_END_TIME: "${{ needs.setup.outputs.endTime }}"
          SRG_EVALUATION_VERSION: "1.0.0"
          SRG_EVALUATION_BUILD_ID: "${{ github.run_id }}"

  deploy:
    needs: evaluation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: deploy easytrade
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f /github/workspace/kubernetes-manifests -n easytrade